### ISSUE TITLE
when I run the program there is no command for like starting the bot

### ISSUE THREAD

**Issue by NumbersTada** [TJC47/someGDbot#2]
![image](https://github.com/TJC47/someGDbot/assets/43664372/8745e0f9-b40e-455c-8754-a1d7e861be7b)

**Comment by TJC47** [comment]
Im Working on a fix rn
should not take long

**Comment by TJC47** [comment]
the issue is that it can't connect to the api

**Comment by TJC47** [comment]
It looks like it can't connect to the API
Please run GDBrowser Locally at Port 80
You can download GDBrowser [Here](https://github.com/GDColon/GDBrowser)
I hope I helped you :)
